-- =============================================================================
-- SECURITY: RBAC ROLES, PRIVILEGES, and DATA MASKING
-- =============================================================================
USE DATABASE UNIVERSITY_DW;

-- ── 1. Create Roles ────────────────────────────────────────────────────────────
CREATE ROLE IF NOT EXISTS UNIVERSITY_ADMIN
    COMMENT = 'Full DW access: DDL + DML + governance';

CREATE ROLE IF NOT EXISTS DATA_ENGINEER
    COMMENT = 'ETL/ELT: full access to STAGING + PROD write';

CREATE ROLE IF NOT EXISTS DATA_ANALYST
    COMMENT = 'Read PROD analytics views; masked PII';

CREATE ROLE IF NOT EXISTS DEPARTMENT_ADMIN
    COMMENT = 'Read own department data only (row-level security)';

CREATE ROLE IF NOT EXISTS INSTRUCTOR
    COMMENT = 'Read own courses and enrolled students only';

CREATE ROLE IF NOT EXISTS STUDENT_PORTAL
    COMMENT = 'Read own academic record only; all PII masked';

CREATE ROLE IF NOT EXISTS READONLY_DASHBOARD
    COMMENT = 'Dashboard service account: aggregated views only';

-- ── 2. Role Hierarchy ──────────────────────────────────────────────────────────
GRANT ROLE DATA_ENGINEER       TO ROLE UNIVERSITY_ADMIN;
GRANT ROLE DATA_ANALYST        TO ROLE UNIVERSITY_ADMIN;
GRANT ROLE DEPARTMENT_ADMIN    TO ROLE DATA_ANALYST;
GRANT ROLE READONLY_DASHBOARD  TO ROLE DATA_ANALYST;

-- ── 3. Warehouse Grants ────────────────────────────────────────────────────────
GRANT USAGE ON WAREHOUSE UNIVERSITY_WH  TO ROLE UNIVERSITY_ADMIN;
GRANT USAGE ON WAREHOUSE UNIVERSITY_WH  TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE REPORTING_WH   TO ROLE DATA_ANALYST;
GRANT USAGE ON WAREHOUSE REPORTING_WH   TO ROLE DEPARTMENT_ADMIN;
GRANT USAGE ON WAREHOUSE REPORTING_WH   TO ROLE READONLY_DASHBOARD;

-- ── 4. Database/Schema Grants ──────────────────────────────────────────────────
-- UNIVERSITY_ADMIN: full
GRANT ALL PRIVILEGES ON DATABASE UNIVERSITY_DW TO ROLE UNIVERSITY_ADMIN;

-- DATA_ENGINEER: full STAGING + read PROD
GRANT USAGE, CREATE TABLE, CREATE STAGE ON SCHEMA UNIVERSITY_DW.STAGING TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES
    IN SCHEMA UNIVERSITY_DW.STAGING TO ROLE DATA_ENGINEER;
GRANT USAGE  ON SCHEMA UNIVERSITY_DW.PROD TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, MERGE ON ALL TABLES
    IN SCHEMA UNIVERSITY_DW.PROD TO ROLE DATA_ENGINEER;

-- DATA_ANALYST: read-only PROD (PII masked via policies)
GRANT USAGE  ON SCHEMA UNIVERSITY_DW.PROD TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA UNIVERSITY_DW.PROD TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA UNIVERSITY_DW.PROD TO ROLE DATA_ANALYST;

-- READONLY_DASHBOARD: restricted to analytics views
GRANT USAGE  ON SCHEMA UNIVERSITY_DW.PROD TO ROLE READONLY_DASHBOARD;
GRANT SELECT ON ALL VIEWS  IN SCHEMA UNIVERSITY_DW.PROD TO ROLE READONLY_DASHBOARD;

-- DEPARTMENT_ADMIN, INSTRUCTOR, STUDENT_PORTAL: object-level via RLS
GRANT USAGE  ON SCHEMA UNIVERSITY_DW.PROD TO ROLE DEPARTMENT_ADMIN;
GRANT SELECT ON ALL VIEWS  IN SCHEMA UNIVERSITY_DW.PROD TO ROLE DEPARTMENT_ADMIN;

-- ── 5. Future Grants ───────────────────────────────────────────────────────────
GRANT SELECT ON FUTURE TABLES IN SCHEMA UNIVERSITY_DW.PROD TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA UNIVERSITY_DW.PROD TO ROLE DATA_ANALYST;